apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infocep-ingress
  namespace: infocep
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: infocep.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infocep-backend
            port:
              number: 80
