apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infocep-ingress
  namespace: infocep
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: infocep.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infocep-backend
                port:
                  number: 80
