name: Build Backend
permissions:
  contents: write
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build-backend:
    uses: valdirsantos714/reusable_workflows/.github/workflows/build-java.yaml@main
    with:
      working-directory: 'infocep'
      java-version: '17'
      push-image: false