name: Build Backend
permissions:
  contents: write
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build-backend:
    uses: ./.github/workflows/build-java.yaml
    with:
      working-directory: 'infocep'
      java-version: '17'
      push-image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      docker-image-name: infocep-backend